version: '1.1.0-{build}'
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
install:
  - dotnet --version
  - dotnet restore
build_script:
  - dotnet build
  - dotnet pack --configuration Release -o artifacts_nuget
test_script:
  - ps: ForEach ($proj in (Get-ChildItem -Path test -Recurse -Filter '*.csproj')) { dotnet test --no-build $proj.FullName }
artifacts:
  - path: '**/artifacts_nuget/*.nupkg'
    name: NuGet Packages
