version: 'pre{build}'
image: Visual Studio 2017
skip_branch_with_pr: true
install:
  - dotnet --version
  - dotnet restore
build_script:
  - dotnet build
  - ps: dotnet pack --version-suffix=${env:APPVEYOR_REPO_BRANCH}-${env:APPVEYOR_BUILD_NUMBER} --configuration Release -o artifacts_nuget
test_script:
  - ps: ForEach ($proj in (Get-ChildItem -Path test -Recurse -Filter '*.csproj')) { dotnet test --no-build $proj.FullName }
artifacts:
  - path: '**/artifacts_nuget/*.nupkg'
    name: NuGet Packages
